// Generated by .NET Reflector from D:\Sfered\Gazelle\Remnants\SferedApi_brep_manipulation.dll
namespace Gazelle
{
    using Rhino.Geometry;
    using System;
    
    public static class SurfaceFunctions
    {
        public static Brep[] PatchHexagon(Curve A, Curve B, Curve C, Curve D, Curve E, Curve F, PatchHexagonStyle style)
        {
            Brep[] brepArray2;
            Curve[] curves = new Curve[] { A, B, C, D, E, F };
            CurveFunctions.FixDirections(ref curves);
            if (style != PatchHexagonStyle.CenterTriangle)
            {
                brepArray2 = null;
            }
            else
            {
                Point3d pointd;
                Point3d pointd2;
                Point3d pointd3;
                Curve[] curveArray2 = A.SplitAt(0.5, out pointd);
                Curve[] curveArray3 = B.SplitAt(0.5, out pointd2);
                Curve[] curveArray4 = C.SplitAt(0.5, out pointd3);
                Curve curve = curveArray2[0];
                Curve curve2 = curveArray2[1];
                Curve curve3 = curveArray3[0];
                Curve curve4 = curveArray3[1];
                Curve curve5 = curveArray4[0];
                Curve curve6 = curveArray4[1];
                LineCurve curve7 = new LineCurve(pointd2, pointd3);
                LineCurve curve8 = new LineCurve(pointd, pointd3);
                LineCurve curve9 = new LineCurve(pointd, pointd2);

                Curve[] curveArray5 = new Curve[] { D, curve2, curve3, curve9 };
                Curve[] curveArray6 = new Curve[] { E, curve4, curve5, curve7 };
                Curve[] curveArray7 = new Curve[] { F, curve6, curve, curve8 };
                Curve[] curveArray8 = new Curve[] { curve7, curve8, curve9 };

                Brep[] brepArray = new Brep[] {
                    Brep.CreateEdgeSurface(curveArray5),
                    Brep.CreateEdgeSurface(curveArray6),
                    Brep.CreateEdgeSurface(curveArray7),
                    Brep.CreateEdgeSurface(curveArray8) };

                brepArray2 = brepArray;
            }
            return brepArray2;
        }
        
        public enum PatchHexagonStyle
        {
            CenterTriangle
        }
    }
}
