// Generated by .NET Reflector from D:\Sfered\Gazelle\Remnants\SferedApi_brep_manipulation.dll
namespace Gazelle.Components
{
    using Grasshopper.Kernel;
    using Rhino.Geometry;
    using Gazelle;
    using Gazelle.Properties;
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    
    public class EmbedProject : GH_Component
    {
        public EmbedProject() : base(SD.Starter + "Project & Embed Curves", SD.Starter + "Prj mbd", SD.CopyRight + "Project and Embed curves to a brep", SD.PluginTitle, SD.PluginCategory8)
        {
        }
        
        protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
        {
            pManager.AddBrepParameter("Brep", "B", "", (GH_ParamAccess)0);
            pManager.AddCurveParameter("Curves", "C", "Curves", (GH_ParamAccess)1);
            pManager.AddVectorParameter("Vector", "V", "Project Vector. This is what both Brep and Curves consider as 'up'.", 0, Vector3d.ZAxis);
        }
        
        protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
        {
            pManager.AddBrepParameter("Brep", "B", "", (GH_ParamAccess)1);
        }
        
        protected override void SolveInstance(IGH_DataAccess DA)
        {
            Brep brep = null;
            List<Curve> curves = new List<Curve>();
            Vector3d vector = Vector3d.Unset;
            DA.GetData<Brep>(0, ref brep);
            DA.GetDataList<Curve>(1, curves);
            DA.GetData<Vector3d>(2, ref vector);
            if (brep != null)
            {
                Brep[] brepArray;
                using (List<Curve>.Enumerator enumerator = curves.GetEnumerator())
                {
                    while (true)
                    {
                        if (!enumerator.MoveNext())
                        {
                            break;
                        }
                        Curve current = enumerator.Current;
                        if ((current == null) || !current.IsValid)
                        {
                            this.AddRuntimeMessage((GH_RuntimeMessageLevel)20, "curve is invalid");
                            return;
                        }
                    }
                }
                BrepFunctions.ProjectEmbed(brep, curves, vector, out brepArray);
                DA.SetDataList(0, brepArray);
            }
            else
            {
                this.AddRuntimeMessage((GH_RuntimeMessageLevel)20, "input bad");
            }
        }
        
        protected override Bitmap Icon =>
            Resources.Sfered_Iconified;
        
        public override Guid ComponentGuid =>
            new Guid("9e2c8ea7-8233-4ef2-b5dd-a652185d6a57");
    }
}
